Bootstrap the project using Blitz.js
CodersCrew/coderscrew-app pull request #6
Opened 2021-05-25 12:24 UTC by kamildzierzak

Closes #1

2021-05-26 15:23 UTC, KonradSzwarc requested changes

2021-05-26 15:23 UTC, KonradSzwarc commented on .env
> +# This env file should be checked into source control
It would be great to put `DATABASE_URL` here, so everyone can run the app locally without the need to do additional configuration.

2021-05-26 15:23 UTC, KonradSzwarc commented on .husky/pre-push
> +#!/bin/sh
For now, it's ok, but we can discuss if we want to run all checks before each push. IMO it would be enough when we run them in CI.

2021-05-26 15:23 UTC, KonradSzwarc commented on README.md
> +# **CodersCrewApp**
This title shouldn't be here as our project title is defined at the top of the README.

2021-05-26 15:23 UTC, KonradSzwarc commented on app/core/components/LabeledTextField.tsx
> +export const LabeledTextField = forwardRef<HTMLInputElement, LabeledTextFieldProps>(
We should use Chakra components here. Now in dark mode (default on my browser), I'm writing white text in a white input 😅

2021-05-26 15:23 UTC, KonradSzwarc commented on app/core/components/Form.tsx
> +        {/* Form fields supplied as children are rendered here */}
Seems intuitive. We can remove this comment 😄

2021-05-26 15:23 UTC, KonradSzwarc commented on package.json
> +  "name": "CodersCrewApp",
Let's make it the same as the repository name

2021-05-27 09:53 UTC, KonradSzwarc approved these changes

2021-05-27 10:38 UTC, Veryyapeee approved these changes

2021-05-31 18:01 UTC, talcia approved these changes

2021-06-01 11:42 UTC, asiaziola approved these changes

2021-06-01 13:43 UTC, merged